#!/bin/bash
# Quick Bundle Demo Script
# Shows all available bundling options for the Apartment Management System

echo "🏠 Apartment Management System - Bundle Options"
echo "==============================================="
echo ""

echo "📦 Available Bundling Methods:"
echo ""
echo "1. 🚀 Bun Bundle (Recommended)"
echo "   - Fast and optimized"
echo "   - Includes all deployment scripts"
echo "   - Creates compressed archive"
echo "   Usage: ./bundle.sh [options]"
echo ""

echo "2. 🐳 Docker Bundle"
echo "   - Containerized deployment"
echo "   - Includes Docker Compose"
echo "   - Production ready"
echo "   Usage: docker-compose up -d"
echo ""

echo "3. 🟢 Node.js Bundle"
echo "   - For environments without Bun"
echo "   - Standard npm deployment"
echo "   - Broader compatibility"
echo "   Usage: .\bundle-node.ps1"
echo ""

echo "4. ☁️ Cloud Platform Ready"
echo "   - Works with Render, Railway, Fly.io"
echo "   - Auto-deployment via Git"
echo "   - Scalable hosting"
echo ""

echo "⚡ Quick Start Commands:"
echo "----------------------"
echo ""
echo "# Create Bun bundle with source code"
echo "./bundle.sh --include-source"
echo ""
echo "# Create clean Docker deployment"
echo "docker-compose up -d"
echo ""
echo "# Create Node.js compatible bundle"
echo ".\bundle-node.ps1"
echo ""
echo "# Test locally first"
echo "bun run dev"
echo ""

echo "📖 For detailed instructions, see:"
echo "   - DEPLOYMENT_GUIDE.md (comprehensive guide)"
echo "   - DEPLOYMENT.md (quick reference)"
echo "   - README.md (project overview)"
echo ""

echo "🔧 Bundle Options:"
echo "------------------"
echo "  --output-dir DIR     Custom output directory"
echo "  --include-source     Include source code"
echo "  --clean             Clean previous bundle"
echo "  --help              Show detailed help"
echo ""

echo "🎯 Choose your deployment method based on:"
echo "   • Bun Bundle: VPS, dedicated servers, development"
echo "   • Docker: Production, microservices, CI/CD"
echo "   • Node.js: Shared hosting, legacy environments"
echo "   • Cloud: Managed hosting, auto-scaling"
echo ""

echo "✨ The apartment management system includes:"
echo "   🏠 Complete booking management"
echo "   📊 Real-time monitoring dashboard"
echo "   📧 Automated email notifications"
echo "   🔐 Role-based access control"
echo "   📱 Responsive mobile design"
echo "   ⚡ High-performance Remix.js"
